### ISSUE TITLE
Boosters Using the Parent Only Work with mvn fabric8:deploy

### ISSUE THREAD

**Issue by sherl0cks** [snowdrop/spring-boot-booster-parent#7]
If you build the booster and then do s2i binary with mvn fabric8:deploy, then the deployment will fail with `no main manifest attribute, in /deployments/<your-app-here>-1.0.0-SNAPSHOT.jar`. The source of the issue if the configuration of the spring-boot plugin: https://github.com/snowdrop/spring-boot-booster-parent/blob/master/pom.xml#L190. This configuration needs to work like the standard spring-boot parent, were the main-class can be specified by end users: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/spring-boot-starter-parent/pom.xml#L165

We should probably also update boosters to set that main class, perhaps somehow set a default. I have no idea how f-m-p is doing it, but these boosters needs to work without f-m-p. 

To reproduce:

```
[your-booster]$ mvn fabric8:deploy -Popenshift
[your-booster]$ mvn clean install
[your-booster]$ oc start-build your-booster-s2i --from-file=target/your-booster-SNAPSHOT.jar
```

**Comment by sherl0cks** [comment]
OK - while the we should still allow end users to configure the main-class, the issue appears to be our use of `classifier`: https://github.com/snowdrop/spring-boot-booster-parent/blob/master/pom.xml#L195.

Thus: 
- `oc start-build <your-build> --from-dir=target/` produces containers with 2 jars and fails at deploy time
- `oc start-build <your-build> --from-file=target/<you-jar>-exec.jar` works as expected, but most spring-boot users will not expect this type of redirect. 

So can we also remove the classifier here? It's a nasty paper cut bug.

**Comment by metacosm** [comment]
@sherl0cks we've removed this parent and we've removed the `exec` classifier so behavior should be closer to what you'd expect from a traditional Spring Boot application. Thanks for the report!
